### ISSUE TITLE
параметр run_away_mode не используется движком?

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#11]
Разобраться с неиспользуемым кодом
`0042B148            call    cai_get_min_hp_`

**Comment by NovaRain** [comment]
Does run_away_mode only work for party members or completely unused?

**Comment by FakelsHub** [comment]
For now, I can not say it.

**Comment by FakelsHub** [comment]
No problem with that.
Just for the NPC, uses the fixed value min_hp. for Party member is calculated min_hp as a percentage of the maximum HP. That the option is used only for Party Members.
