### ISSUE TITLE
Energy weapon flag

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#14]
Имеется один свободный бит для указания того, что оружие будет принудительно использовать навык Энергетического оружия.
```
0х0018 Weapon Flags (флаги оружия):
0x00000100 – Big Gun (оружие относится к классу Big Guns)
0x00000200 – 2Hnd (оружие относится к классу двуручных)
0x00000400 – Energy Gun
```
Вставить хак в: 0x47831E

**Comment by NovaRain** [comment]
Well, the issue on NMA can be solved by hook script.

**Comment by FakelsHub** [comment]
through the script, your crutch turns out to be bad, imagine that there are two hooks for damage calculate. therefore, your crutch must always perform last !

**Comment by FakelsHub** [comment]
may need to add one additional hook "attack" start/end еvent
I have long wanted to introduce it but something constantly distracted me from adding it.

**Comment by NovaRain** [comment]
> may need to add one additional hook "attack" start/end еvent
> I have long wanted to introduce it but something constantly distracted me from adding it.

Doesn't AfterHitHook get triggered right before an attack?

EDIT: about the EW flag, is this code OK?
```
static const DWORD item_w_skill_break = 0x478332;
static void __declspec(naked) item_w_skill_hook() {
    __asm {
        mov  eax, [esp + 4];
        test byte ptr [eax + 0x19], 4;
        jnz  energy;
        xor  eax, eax;
        jmp  item_w_damage_type_;
energy:
        add  esp, 4;
        jmp  item_w_skill_break;
    }
}

HookCall(0x47831E, item_w_skill_hook);
```

**Comment by FakelsHub** [comment]
HOOK_AFTERHITROLL - executed after HOOK_TOHIT

```
static void __declspec(naked) item_w_skill_hook() {
    __asm {
        mov  edx, [esp + 4]; // item proto
        test byte ptr [edx + 0x19], 4; // weapon.flags_ext
        jnz  energy;
        mov  edx, ebx;
        jmp  item_w_damage_type_
energy:
        inc  eax; // DMG_laser  
        retn;
    }
}
```

**Comment by NovaRain** [comment]
Isn't 0x19 `weapon.Weapon` (part of flags_ext)?

**Comment by FakelsHub** [comment]
да
