### ISSUE TITLE
Приоритет для hs_* скриптов.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#15]
Изменить порядок выполнения для hs скриптов, так чтобы они выполнялись перед подписанными обработчиками в gl скриптах.

**Comment by FakelsHub** [comment]
Так же добавить функцию позволяющей задать приоритет выполнения hook обработчика для register_hook_proc функции относительно других обработчиков, при этом register_hook должен всегда иметь наивысший приориет, но не выше чем у hs_ скрипта..

**Comment by FakelsHub** [comment]
(После реализации добавить описание порядока выполнения скриптов в документацию sfall.)

**Comment by NovaRain** [comment]
Oh, I thought hs_ always has higher priority than global script.
I tried running a hs_tohit and a gl0tohit (both just print msg) and gl is executed before hs_. I think that means hs_ can override the result in gl?

**Comment by FakelsHub** [comment]
Сейчас выполняется все в обратном порядке (метод **LIFO**), т.е первый добавленный обработчик выполняется последним, ( самым первым добавляемым скриптом является hs_ скрипты.) Тогда получается, что обработчик в hs_ скрипте является последним головным обработчиком куда стекаются все изменения произведенные в gl обработчиках, в принципе это логично сделано, **и тогда менять ничего не нужно.**

!!! Но сейчас имеется не разрешаемый конфликт скриптов hs_barterprice из ECCO и gl_ обработчика в скрипте фильтра. Т.е. при такой конфигурации скрипт из Ecco должен **всегда выполняться первым**, а затем уже обработчики из gl скриптов.

**Comment by FakelsHub** [comment]
> Oh, I thought hs_ always has higher priority than global script.
> I tried running a hs_tohit and a gl0tohit (both just print msg) and gl is executed before hs_. I think that means hs_ can override the result in gl?

yes, that’s what it was intended to be.

**Comment by FakelsHub** [comment]
Хм. Тогда получается, что нужна дополнительная функция позволяющаяя зарегистрировать скрипт после  hs_ скриптом, (т.е. в программном смысле поместить скрипт в начало вектора).

>Hm. Then it turns out that an additional function is needed that allows you to register the script before the hs_ script (i.e., in the programmatic sense, put the script at the beginning of the vector).

**Comment by FakelsHub** [comment]
Нужно ли изменять поведение для `register_hook` так, что бы зарегистрировать скрипт непосредственно перед hs_ скрипта? или же это оставить как есть.

>Do I need to change the behavior for `register_hook` so that I register the script immediately after the  hs_ script? or leave it as is.

**Comment by NovaRain** [comment]
> 
> 
> Нужно ли изменять поведение для `register_hook` так, что бы зарегистрировать скрипт непосредственно после hs_ скрипта? или же это оставить как есть.
> 
> > Do I need to change the behavior for `register_hook` so that I register the script immediately after the  hs_ script? or leave it as is.

I'm not sure what's the current order of execution for the same hook. Is it:
register_hook in global script (because of `start` proc) -> register_hook_proc in global script -> hs_* script (executed at the last, highest priority)

The global scripts themselves are executed by filename order, at least for two global scripts `gl_0000` and `gl_0001` the 0000 runs first.

**Comment by FakelsHub** [comment]
The execution order of the `register_hook_proc` handlers and `register_hook` is carried out according to the LIFO principle. The last registered is executed first.

**Comment by FakelsHub** [comment]
Gl_01 - register_hook_proc
Gl_02 - register_hook
Gl_03 - register_hook_proc
Order chain in game: 
`execute Gl_01 -> hook trigger -> run hook_proc gl_03 -> hook gl_02 -> hook_proc gl_01-> hs_hook -> (execute GL_02) -> execute Gl_03`
To:
`-> hook trigger -> run hook_proc gl_03 -> hook_proc gl_01-> hook gl_02 -> hs_hook ->`

**Comment by NovaRain** [comment]
Uh, now my head hurts... Let's see if I understand the example correctly:
When the game starts, sfall should first check and register `hs_blah.int` in the chain.
Then it runs through all global scripts and registers `register_hook`:
* Run gl_02's `start`, register the script in the chain.

Then it registers `register_hook_proc`, following the filename order:
* Run gl_01's `start`, register its hook_proc in the chain.
* Run gl_03's `start`, register its hook_proc in the chain.

Since the chain itself follows LIFO (stack) principle, when HOOK_BLAH is triggered, sfall runs:
1. `gl_03 hook_proc`
2. `gl_01 hook_proc`
3. `gl_02 (start)`
4. `hs_blah.int` (last, can override the result from all above)

EDIT: OK, I made four test scripts like the example. The current order of execution in game is:
`gl_0003 hook_test` -> `gl_0002` -> `gl_0001 hook_test` -> `hs_tohit`
for both 4.x and 3.8.
[hook_order_test.zip](https://github.com/FakelsHub/sFall-Extended/files/3482484/hook_order_test.zip)

**Comment by FakelsHub** [comment]
Changes to the start of scripts will not be affected.
```
    Run gl_01's start, register its hook_proc in the chain.
Run gl_02's start, register the script in the chain.
    Run gl_03's start, register its hook_proc in the chain.
```
We get it as you wrote.
```
    gl_03 hook_proc
    gl_01 hook_proc
    gl_02 (start)
    hs_blah.int (last, can override the result from all above)
```

**Comment by NovaRain** [comment]
> We get it as you wrote.
> 

Do you mean you got a different result in the current build (my test scripts should be the same as your example right?), or you're proposing to change the order like in your example above?

**Comment by FakelsHub** [comment]
It is how I suggest changing.

Current: `gl_0003 hook_test -> gl_0002 -> gl_0001 hook_test -> hs_tohit`

**Comment by FakelsHub** [comment]
But then if don't make many changes in the sfall code for register_hook, the principle will change from LIFO to FIFO
```
gl_01 - register_hook_proc
gl_02 - register_hook
gl_03 - register_hook_proc
gl_04 - register_hook

Run:
1.   gl_03 hook_proc
2.   gl_01 hook_proc
3.   gl_02 (start)
4.   gl_04 (start)
5.   hs_blah.int (last, can override the result from all above)
```
So I think it's worth changing it.

**Comment by NovaRain** [comment]
Honestly for me `register_hook(HOOK_BLAH)` basically equals to `register_hook_proc(HOOK_BLAH, start)`, so I never thought there should be a priority difference between the two.

What about the new function of sorting the order?

**Comment by FakelsHub** [comment]
> What about the new function of sorting the order?

No. Too much will need to be changed + logic complication.

**Comment by NovaRain** [comment]
```
1.   gl_03 hook_proc
2.   gl_01 hook_proc
3.   gl_02 (start)
4.   gl_04 (start)
```
I think this order is kinda weird/inconsistency, considering for `register_hook_proc` and `register_hook` the sqeuence is reversed.

**Comment by FakelsHub** [comment]
> so I never thought there should be a priority difference between the two.

I plan to add a new register_hook_proc which would add the script to the end (after hs_), according to the FIFO principle.
```
gl_01 - register_hook_proc
gl_02 - register_hook_proc_last
gl_03 - register_hook_proc
gl_04 - register_hook_proc_last
...
1.   hs_blah.int (last, can override the result from all above)
2.   insert gl2 new_register_hook_proc
3.   insert gl4 new_register_hook_proc
```
> Hopefully it's not some super code overhaul and I can backport it to 3.8.

If to insert using the FIFO method, then the changes will be minimal, a couple of lines of new code.

**Comment by NovaRain** [comment]
So it's just a new `register_hook_proc_last` that makes the hook_proc being registered in the chain after hs_? The rest are still in the current order?
(In the case of six gl scripts and one hs_)
```
gl_01 - register_hook_proc
gl_02 - register_hook
gl_03 - register_hook_proc
gl_04 - register_hook
gl_05 - register_hook_proc_last
gl_06 - register_hook_proc_last
```
`gl_04` -> `gl_03 hook_test` -> `gl_02` -> `gl_01 hook_test` -> `hs_tohit` -> `gl_06 hook_last` -> `gl_05 hook_last`

**Comment by FakelsHub** [comment]
so
> gl_04 -> gl_03 hook_test -> gl_02 -> gl_01 hook_test -> hs_tohit -> gl_0**5** hook_last -> gl_0**6** hook_last

**Comment by NovaRain** [comment]
I still think 06 -> 05 (LIFO?) is more consistent with how other two `register_hook*` functions get sorted. Or does it require too much code change?

**Comment by FakelsHub** [comment]
In this case, **_last** implies that this should be the last in the chain.

**Comment by FakelsHub** [comment]
> Or does it require too much code change?

a little more, then you have to control the position of the hs_ script in the vector.

**Comment by NovaRain** [comment]
Oh, is `register_hook_proc_last(HOOK_BLAH, hook_proc)` in 05 & 06 like:
sfall runs gl_05 and puts its hook_proc at the end of the chain.
Then sfall runs gl_06 and puts its hook_proc at the end of the chain. Now 06's hook_proc is the last one of all procs for the same hook.

**Comment by FakelsHub** [comment]
I don’t understand what is wrong in your message? :)

**Comment by NovaRain** [comment]
> 
> 
> I don’t understand what is wrong in your message? :)

No, just want to make sure I understand the new `register_hook_proc_last` you're planning.
The order in [your post](https://github.com/FakelsHub/sFall-Extended/issues/15#issuecomment-519599390) above does sound more reasonable.

**Comment by burner1024** [comment]
Wait wait wait. I would really like to avoid execustion order arms race in scripts.

> !!! Но сейчас имеется не разрешаемый конфликт скриптов hs_barterprice из ECCO и gl_ обработчика в скрипте фильтра. Т.е. при такой конфигурации скрипт из Ecco должен **всегда выполняться первым**, а затем уже обработчики из gl скриптов.

1. What exactly is the conflict and why is it unsolvable?
1. And if it's indeed unsolvable by both mods **design**, why add more stuff to let one override another, instead of properly marking them as incompatible, which they are in that case?

**Comment by FakelsHub** [comment]
Test log
```
Loading hook scripts
>scripts\hs_keypress.int Done id = 020a3d28
Finished loading hook scripts

Loading global scripts
Found global scripts: gl_ainvenfilter.int
Found global scripts: gl_ammomod.int
Found global scripts: gl_bhooktest.int
Found global scripts: gl_highlighting.int
Found global scripts: gl_partycontrol.int
Found global scripts: gl_sfall-mods.int
Found global scripts: gl_whooktest.int
Found global scripts: gl_yhooktest.int

>scripts\gl_ainvenfilter.int Done
Global script: 020a3dc8 registered as hook ID 19
 script: 020a3d28 (hs_)
 script: 020a3dc8

>scripts\gl_bhooktest.int Done (register_hook)
Global script: 020a753c registered as hook ID 19
 script: 020a3d28 (hs_)
 script: 020a753c <- insert
 script: 020a3dc8
 
>scripts\gl_highlighting.int Done
Global script: 020a7964 registered as hook ID 19
 script: 020a3d28 (hs_)
 script: 020a753c
 script: 020a3dc8
 script: 020a7964

>scripts\gl_sfall-mods.int Done
Global script: 020a7c58 registered as hook ID 19
 script: 020a3d28 (hs_)
 script: 020a753c
 script: 020a3dc8
 script: 020a7964
 script: 020a7c58

>scripts\gl_whooktest.int Done (register_hook_proc_spec)
Global script: 020b7490 registered as hook ID 19
 script: 020b7490 <- insert spec
 script: 020a3d28 (hs_)
 script: 020a753c
 script: 020a3dc8
 script: 020a7964
 script: 020a7c58
 
>scripts\gl_yhooktest.int Done (register_hook)
Global script: 020b7a20 registered as hook ID 19
 script: 020b7490
 script: 020a3d28 (hs_)
 script: 020a753c <- register_hook
 script: 020b7a20 <- insert register_hook
 script: 020a3dc8
 script: 020a7964
 script: 020a7c58
Finished loading global scripts
+
>scripts\gl_zhooktest.int Done (register_hook_proc_spec)
Global script: 020b71c0 registered as hook ID 19
 script: 020b71c0 <- insert spec
 script: 020b6b90 <- spec
 script: 020a3428 (hs_)
 script: 020a6c3c <- register_hook
 script: 020b7120 <- register_hook
 script: 020a34c8
 script: 020a7064
 script: 020a7358
Finished loading global scripts
```

**Comment by NovaRain** [comment]
So with the new commit, does the order of execution become:
1. hooks registered with `register_hook_proc`
2. hooks registered with `register_hook`
3. hs_ scripts
4. hooks registered with new `register_hook_proc_spec`

Just curious if it's much simpler to convert EcCo's hs_barterprice to normal global script with register_hook* and change its filename to re-sort the order.

**Comment by FakelsHub** [comment]
> with the new commit, does the order of execution become:

Yes.

> hs_barterprice to normal global script with register_hook* 

No problem

**Comment by NovaRain** [comment]
> > hs_barterprice to normal global script with register_hook*
> 
> No problem

I mean the whole "re-order hooks execution and new function" seems a bit overkill if the problem you have with EcCo and your inven filter can be solved in the "convert hs_ to gl" way. Well, technically the change shouldn't effect too much on current RP/TCs unless the player also installed bunch of other gameplay mods.

**Comment by FakelsHub** [comment]
Here, rather, a certain guarantee is needed that the script will be executed last.
re-order the execution by changing the names of the scripts is a bad job.

**Comment by NovaRain** [comment]
> 
> 
> Here, rather, a certain guarantee is needed that the script will be executed last.
> re-order the execution by changing the names of the scripts is a bad occupation.

But even with new `register_hook_proc_spec`, the order of execution of multiple procs using it are still depend on their gl filename right? IMO it's just like changing "mod order" like in Beth games.

**Comment by FakelsHub** [comment]
Right. The consistent execution of all scripts, we can not avoid.

**Comment by FakelsHub** [comment]
another system may be needed, based not on the names of the scripts, but on the position of the mod in the folders / listing of mods, while the current script execution system would operate inside the mod.

**Comment by NovaRain** [comment]
I don't know, that sounds even more complex.

**Comment by FakelsHub** [comment]
it’s not difficult, just a few new lines of code. XD

**Comment by FakelsHub** [comment]
*It new feature for sfall 5.0

**Comment by NovaRain** [comment]
What? Are you going to jump the major version number?

**Comment by burner1024** [comment]
I still don't understand what is the problem between EcCo and inventory filter in the first place.

Moreover, only _one_ script can be executed _last_. So all mods using that feature will be incompatible. But in that case, they can be simply marked as such.

**Comment by NovaRain** [comment]
Not strictly incompatible, it just creates another case for execution order race, same as current register_hook/register_hook_proc, only it happens after hs_* script. If there are two scripts and a hs_* script :
* gl_001 with `register_hook_proc_spec(HOOK_FOO, my_great_mod);`
* gl_002 with `register_hook_proc_spec(HOOK_FOO, my_awzom_mod);`

When the "foo" hook is triggered, hs_foo.int runs first, then my_great_mod in gl_001, then my_awzom_mod in gl_002.

EDIT: hmm, the change actually makes the hook use case more unnecessarily complex.
Before/currently the hook execution order is only depend on global script filenames (`register_hook` and `register_hook_proc` are equal), with the unique hs_* script always being executed last. As long as there is no hs_* script (which is really not a recommended way to use hooks), the whole "race" problem is much simpler since it's only about sorting filenames.

After the change you'll get three classes of order races:
1. `register_hook_proc`, and the order between them is depend on filenames of their scripts.
2. `register_hook`, also depend on filenames.
3. hs_* script (it's unique so no race)
4. `register_hook_spec`, yet again depend on filenames.

**Comment by phobos2077** [comment]
I may be blind but I couldn't find the explanation of the core problem - what is the conflict between 2 mods?
I'm not sure if messing with order of hook scripts is useful at all. If one mod breaks another mod because they were loaded in the wrong order - there are 3 solutions:

- Declare them as incompatible
- Modify one of them (or both) to be compatible
- Rename script files to force correct execution order

The only place where manual reordering of hook scripts might be useful is when one mod needs several handlers of the same hook for some reason (though this can probably be avoided using one handler and just calling a bunch of procedures from it).

PS: I know you can do whatever you want with your fork, but more logic and functionality isn't always the best solution. Good software engineering is finding the simplest possible solution for the actual problem of today, while allowing painless extension for the expected future problems (without implementing any features or complicating the architecture before it's required).

**Comment by FakelsHub** [comment]
Несовместимость между двумя модами появится только тогда, когда будет невозможно разрешить  конфликт в очередности их выполнения.
В данном случае механика в скрипте фильтра требует чтобы hook бартера выполнялся самым последним.

**Comment by NovaRain** [comment]
It doesn't work if converting EcCo's hs_barterprice to some gl_z_eccobarter to make it run after your inven filter?

**Comment by FakelsHub** [comment]
И что?, появится другой скрипт который зарегистрируется после. Я же написал что нужна некая гарантия (пусть даже псевдо), того что скрипт будет выполняться последним.
Когда появится два скрипта которые должны выполнятся последними, тогда и наступит та самая не совместимость между модами о которой вы говорите.

And what?, another script will appear that will register after. I wrote that we need some kind of guarantee (even it’s pseudo) that the script will be executed last.
When two scripts appear that should be executed last, then the same incompatibility between the mods your are talking about will come.

**Comment by FakelsHub** [comment]
>  Are you going to bump the major version number?

no.

**Comment by NovaRain** [comment]
> And what?, another script will appear that will register after. I wrote that we need some kind of guarantee (even it’s pseudo) that the script will be executed last.
> When two scripts appear that should be executed last, then the same incompatibility between the mods your are talking about will come.

IMO your `register_hook_proc_spec` doesn't really solve the issue, it simply creates a seperate "race" for procedures registered with the new function. I think there shouldn't be any difference between old register_hook and register_hook_proc (i.e. keep their behavior as before, their order purely based on script filenames, then hs_ script, then register_hook_proc_spec). At least you only get one more "race" with register_hook_proc_spec to deal with, not three for each function as in your current commit.

BTW, why it's called _spec not something like _last? _spec for special?

**Comment by FakelsHub** [comment]
A new register_hook option is needed to reduce one “big race” based on file names.
Moreover, register_hook is not the same as register_hook_proc, register_hook is essentially an hs_ script with one hook and an arbitrary name, and it is very limited.
I see no problem with the new register_hook, now it takes precedence, just like the hs_ script.
As for me in the sfall code there is a complete mess with registration, nothing is standardized.

**Comment by FakelsHub** [comment]
> _spec for special?

yes, for exceptional situations, I think "spec" hints at it.

**Comment by NovaRain** [comment]
> 
> 
> A new register_hook option is needed to reduce one “big race” based on file names.

But in reality you have already increase the number of races from one (filenames only) to three (filenames for each register_hook* functions). If you keep old behavior for register_hook, at least there will be only two races (new register_hook_proc_spec and old register_hook* functions). And your goal was to need some hook to "run last", which is done by the new register_hook_spec, why not just keep other old ones in their default behavior? I think that's a good compromise for keeping compatibility (existing scripts still work in exactly the same order) while solving your problem (new script with register_hook_proc_spec runs last to avoid certain issues).

For gl_001~004 + hs_* script, before the execution chain was:
* gl_004 (register_hook) -> gl_003 (register_hook_proc) -> gl_002 (register_hook_proc) -> gl_001 (register_hook) -> hs_*

The only race (or order sorting) was depend on the filenames of gl_001~004.

With your commit it becomes:
1. gl_003 (register_hook_proc) -> gl_002 (register_hook_proc) ->
2. gl_004 (register_hook) -> gl_001 (register_hook) ->
3. hs_ script ->
4. gl_005 (register_hook_proc_spec) -> gl_006 (register_hook_proc_spec)

Each register_hook* function has its own sorting to deal with, like the weight class in boxing.

> Moreover, register_hook is not the same as register_hook_proc, register_hook is essentially an hs_ script with one hook and an arbitrary name, and it is very limited.
> I see no problem with the new register_hook, now it takes precedence, just like the hs_ script.
> As for me in the sfall code there is a complete mess with registration, nothing is standardized.

From my POV `register_hook` is more like a shortcut for `register_hook_proc(HOOK_FOO, start)` (that works the same as register_hook(HOOK_FOO), so suddenly it becomes "lower" in execution chain?), not the same as hs_* script itself.

> 
> 
> > _spec for special?
> 
> yes, for exceptional situations, I think "spec" hints at it.

For abbreviation like "spec" itself my first impression is "specification" not "special".

**Comment by FakelsHub** [comment]
I do not see a problem with the new register_hook, show me scripts that depend on the position of the register_hook script, are there any?

With the new register_hook, we can change the position regardless of the script name, this will give the outdated little-used function new features.
I think that the time has come (sfall version) when need to change something in the registration, especially since there is an analogue in the form of `register_hook_proc(HOOK_FOO, start)` to replace register_hook and not break anything.

Can make the new option of enable a new registration behavior for register_hook if you are so worried about compatibility?
But I repeat that I don’t see a large problem in register_hook change.

**Comment by NovaRain** [comment]
> With the new register_hook, we can change the position regardless of the script name

It's not true, `register_hook` position is still depend on its script name, just not mixing with scripts using `register_hook_proc`. Like I said above, you just separate all three of them and now they have their own filename sorting, which does _increase_ the complexity on execution order.

> Can make the new option of enable a new registration behavior for register_hook if you are so worried about compatibility?
> But I repeat that I don’t see a large problem in register_hook change.

Sure. But I can say the same thing that not seeing any reason changing existing register_hook/_proc, since you already got what you want with register_hook_proc_spec. And for me `register_hook` isn't "outdated little-used function", modder can choose what he prefers when writing hook scripts (if the script itself is a simple hook, maybe just use register_hook; if there's a need to put several hooks in the same script, use register_hook_proc)

**Comment by FakelsHub** [comment]
The documentation says it's preferable to use register_hook_proc.
And you yourself said that `register_hook(HOOK) == register_hook_proc(HOOK, start)`
what is the difficulty of using register_hook_proc instead of register_hook, is it a simple script or not - it makes no difference.

**Comment by NovaRain** [comment]
OK. I'm still curious if converting EcCo's hs_barterprice to gl_ script and renaming it to run after your inven filter script fixes your issue. (didn't see you answer this)

**Comment by FakelsHub** [comment]
> I'm still curious if converting EcCo's hs_barterprice to gl_

yes, this solves the problem + adding function set_sfall_arg() to it
but it breaks EcCo's since it should be executed after all other scripts.
iI need to change the name to gl_#_filte,, to be sure that no one will register a hook before it, and renaming hs_barterprice to gl_a_barterprice
something like this.

**Comment by burner1024** [comment]
> I may be blind but I couldn't find the explanation of the core problem - what is the conflict between 2 mods?

I keep saying that and there's no response.

> I'm not sure if messing with order of hook scripts is useful at all. If one mod breaks another mod because they were loaded in the wrong order - there are 3 solutions:
> 
>     * Declare them as incompatible
> 
>     * Modify one of them (or both) to be compatible
> 
>     * Rename script files to force correct execution order

And that too.

**Comment by FakelsHub** [comment]
> I keep saying that and there's no response.

Давно уже написал, что конфликт в очередности выполнения.

**Comment by burner1024** [comment]
> Давно уже написал, что конфликт в очередности выполнения.

Не знаю как кому-то еще, но мне это ни о чем не говорит. Конкретно-то в чем проблема? Может быть можно переделать, чтобы конфликта не было?
