### ISSUE TITLE
User could override the path that scripts read their .ini config files

### ISSUE THREAD

**Issue by ghost** [FalloutTeamX/sfall-Extended#16]
mod makers use different paths for their config files and they seem to be all over the place. it would be nice to be able to place them all in one directory e.g. configs/

**Comment by FakelsHub** [comment]
This is a question for the modders: Why do they place their configs in different path, and not for example in "\configs" :)
The user cannot redefine the folder where the config file is located without recompiling the mod script.

**Comment by FakelsHub** [comment]
I think, I came up something. :)

**Comment by NovaRain** [comment]
I don't think it's a good idea to let users override all paths specified in `get/set_ini_*` functions with non-scripting method. Issues related to scripting should be solved in scripting ways (recompiling the script, asking modders (who?) to reorganize their scattered ini files, etc.), not by some override setting in ddraw.ini.

**Comment by ghost** [comment]
it is not a big deal I dont have to access these file that often. This is probably my ocd and not thinking this through.

btw. I just learned what sym and hardlinks can do.

**Comment by FakelsHub** [comment]
For example, it annoys me when all the ini files of scripts are in the root folder, (or somewhere else) and I don’t really want to recompile the script files.
And when it will be in the same folder, it will lead to order in the files.

**Comment by FakelsHub** [comment]
Done.

**Comment by FakelsHub** [comment]
Done.

**Comment by FakelsHub** [comment]
Добавить опцию для указания списка имен ini файлов, для которых не должен переопределяться путь, по аналогии как с ddraw/f2_res.ini (**не требуется, устарело**)

**Comment by burner1024** [comment]
Seems like a kludge upon a kludge. There's `mods` directory already, I think it's quite enough to hold both mods and their inis.

> This is a question for the modders: Why do they place their configs in different path, and not for example in "\configs" :) 

Because no one told them to do otherwise.

> asking modders (who?) to reorganize their scattered ini files, etc.), not by some override setting in ddraw.ini.

I remember proposing to define a best practice for mod packaging, and you said you were explicitly uninterested in that.

**Comment by NovaRain** [comment]
> I remember proposing to define a best practice for mod packaging, and you said you were explicitly uninterested in that.

Yes, and am still uninterested. Since now there's already the option people are free to change it to whatever they want.

**Comment by burner1024** [comment]
Well, that's the reason it's a dump.

**Comment by FakelsHub** [comment]
@burner1024 что не так?

**Comment by burner1024** [comment]
Ну ты же знаешь, я всегда за то чтобы было больше опций... кроме случаев когда они только вносят хаос или исключительно предоставляют возможность выстрелить себе в ногу.
Конкретно в этом случае, мне кажется, что умнее наоборот, стандартизировать формат модов как можно сильнее, а не предоставлять возможность мусорить дальше. Я бы даже папку `mods` _захаркодил_ бы, потому что никакого реального смысла менять путь к ней нет.

Ну а так, если хочется, особых возражений нет, не мне же делать. Просто на мой взгляд это костыль к проблеме, которая решается в другом месте.

**Comment by FakelsHub** [comment]
> Я бы даже папку mods захаркодил бы, потому что никакого реального смысла менять путь к ней нет.

Если ее захардить то нужно где-то упомянуть, что есть такая-то новая папка и для чего она нужна. Можно будет позже удалить опцию.

> Конкретно в этом случае, мне кажется, что умнее наоборот, стандартизировать формат модов как можно сильнее, а не предоставлять возможность мусорить дальше.

Непредставяю, как это можно сделать.

> Просто на мой взгляд это костыль к проблеме, которая решается в другом месте.

Не понял чем тебе опция не понравилать, и ты о какой? которую я хочу добавить, или которая уж есть?

**Comment by burner1024** [comment]
> Непредставяю, как это можно сделать.

Ну как, просто в документации написать: вот так делать хорошо, а вот так делать плохо, а причины этого вот такие. Т.е. направить моддеров по правильному пути, а не направлять пользователей расчищать за моддерами их конюшни.

> Не понял чем тебе опция не понравилать, и ты о какой? которую я хочу добавить, или которая уж есть?

Мне кажется, что первая настройка это костыль, а вторая это костыль к костылю.
Проблема в том, что в директории игры помойка. Корень этой проблемы в том, что нет никакого стандарта, даже рекомендательного, который говорит куда что класть. И такой стандарт могут задать только те, кто собственно работает над sfall. @phobos2077 не хочет, @NovaRain тоже не хочет. Вот и получается то, что получается.

**Comment by FakelsHub** [comment]
Тогда может сделать поиск ini файлов в директории mods\ и в корне игры если не указан к ini файлу путь?

**Comment by burner1024** [comment]
> Тогда может сделать поиск ini файлов в директории mods\ и в корне игры если не указан к ini файлу путь?

Нормальный вариант, если еще указать, что предпочтительно класть в mods, я думаю этого будет более чем достаточно.

**Comment by FakelsHub** [comment]
Изменил опцию.
Теперь поиск(чтение) файла будет происходить относительно пути указанному в опции **IniConfigFolder** при этом если файл не будет найден, поиск продолжится как обычно относительно корневого каталога игры.
