### ISSUE TITLE
Излишний код в main.cpp

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#17]
https://github.com/FakelsHub/sFall-Extended/blob/beaf9be117a9940189d077a6902380ce7571ae76/sfall/main.cpp#L106

Вроде функция trim() является лишней потому как сама GetPrivateProfileStringA обрезает пробелы по краям.
Нужно это проверить.

**Comment by NovaRain** [comment]
I tried inserting a string printing test in `GetIniString()`:
```
GetPrivateProfileStringA(section, setting, defaultValue, buf, bufSize, iniFile);
dlog_f("\nIni string test: %s\n", DL_INIT, buf);
std::string str(buf);
```
And change an option in ddraw.ini with leading and trailing spaces like this:
```
ElevatorsFile   =   Elevators.ini    <-4 trailing spaces
```
The result line in sfall-log.txt is: `Ini string test: Elevators.ini` without any extra spaces.
I guess that's a failsafe if someone purposefully uses quotation marks like this:
```
ElevatorsFile   ="   Elevators.ini    "
```

**Comment by FakelsHub** [comment]
> I guess that's a failsafe if someone purposefully uses quotation marks like this:

Using here trim()  is an error, for the reason below.
```
std::string Translate(const char* section, const char* setting, const char* defaultValue, size_t bufSize) {
	return GetIniString(section, setting, defaultValue, bufSize, translationIni);
}
```
I've already redid everything, but have not yet uploaded the changes.

**Comment by NovaRain** [comment]
> Using here trim() is an error, for the reason below.

You mean if in some cases it requires leading or trailing spaces for translation string?

> I've already redid everything

Wait, everything of what?
