### ISSUE TITLE
Проблемы адресов (список)

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#20]
Мои текушие проблемы:
`0x423deb` - конфликт перезаписи (можно исправить ситуацию)
`0x4c21fd`  - конфликт перезаписи (попробовать исправить ситуацию)
`0x4c6162` - конфликт перезаписи (попробовать исправить ситуацию)
`0x42a14f` -  не является конфликтом
`0x42a178` - не является конфликтом

Нет конфликтов. (После повторной загрузки)
```
Boxes
0x461266 L:4 [Overwriting]
0x4612ac L:4 [Overwriting]
0x461374 L:4 [Overwriting]
0x4613e8 L:4 [Overwriting]
0x461479 L:4 [Overwriting]
0x46148c L:4 [Overwriting]
0x4616bb L:4 [Overwriting]
0x46133c L:4 [Overwriting]
0x4612fe L:4 [Overwriting]

Reset:
0x424ab6 L:1 [Overwriting]
0x43c27a L:1 [Overwriting]
0x496880 L:4 [Overwriting]
0x4afab8 L:1 + 0x4afab9 L:4 [Overwriting]
0x4afbc1 L:1 [Overwriting]
0x4c06d1 L:5 [Overwriting]
0x4c2d9b L:4 [Overwriting]
```

**Comment by FakelsHub** [comment]
Нужно составить список всех адресов используемых в скриптовых функциях и тех которые втраиваются в код по мере использования функций, и проверить это на наличее конфликтов.

**Comment by FakelsHub** [comment]
Scripting: Misc.cpp
```
0x495C50 - 4
0x495C77 - 6
0x495CEC - 6
0x495CFB - 1
0x495BF1 - 5
0x4AFBC1 - 1
0x4AFC1C - 2
```

**Comment by FakelsHub** [comment]
Чето это какая-то херня, нужно написать отдельную программу, которая будет искать ключевые слова в файлах проекта sfall и проверять найденные адреса на наличее конфликтов.
Займусь этим поле выпуска версии.

**Comment by NovaRain** [comment]
Do the addresses in Misc.pp really conflict with others? Seems to me that's just due to npc leveling function changing/resetting the addrs when needed?

**Comment by FakelsHub** [comment]
No, I'm just making a list, which I will delete later.

**Comment by FakelsHub** [comment]
Есть идея, создать отдельный модуль для отладочной версии sfall, в который будут помещаться все адреса, таким образом при запуске будет происходить проверка на конфликты.
Минус этого в том, что прийдется писать адреса вручную :(

**Comment by NovaRain** [comment]
The current checking in SafeWrite is not good enough?

**Comment by FakelsHub** [comment]
it checks not all available addresses.

**Comment by FakelsHub** [comment]
Нужно еще добавить список всех адресов возврата jmp, так как есть небольшая вероятность прыгнуть на хакнутый код.
