### ISSUE TITLE
Найти NPC по его cкрипт ID.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#25]
Добавить функцию(обвертку) для поиска npc на текущей карте по номеру индекса его cкрипта.

**Comment by NovaRain** [comment]
If there are several critters sharing the same script (e.g. guards in a town), who will it return, or it returns an array of pointers of all critters? Currently I think it can be done like this?
```
foreach (who in list_as_array(LIST_CRITTERS)) begin
   if (get_object_data(who, 0x80) == scriptIdx) then begin
      // do things or add to an array for later use
   end
end
```

**Comment by FakelsHub** [comment]
it is so simple, then I do not need to add anything.
