### ISSUE TITLE
Функция "get_object_under_cursor"

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#26]
Функция иногда возвращает объект курсора, т.е. сам себя, так же по какой-то причине не всегда возвращается объект находяшийся под курсором.
По видимому проблема кроется в самой движковой функции.

**Comment by NovaRain** [comment]
`obj_under_cursor`? Do you have an example that can reproduce the issue reliably?

**Comment by FakelsHub** [comment]
All Ok. just wrong to used the function.

**Comment by FakelsHub** [comment]
Все-же не дает мне покоя это странное поведение функции, когда курсор находится в режиме гексового курсора.
Единственный вариант это запретить использование функции для неверного режима курсора и возвращать нулевой объект.

**Comment by NovaRain** [comment]
What's wrong with the movement (hex) cursor? You mean it's hard to determine the "real" pointer position from the look?

**Comment by FakelsHub** [comment]
I mean that the function is not designed for use when using movement cursor. (it's just buggy).
We either need to disable it for this mode, or add an additional wrapper for the function that would return the object pointed to by the hex cursor.

**Comment by FakelsHub** [comment]
[Fixed.](https://github.com/FakelsHub/sFall-Extended/commit/34dbaa83265759f22f0182c654d2bcef50e7256d)
