### ISSUE TITLE
Get mouse position on worldmap.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#29]
HRP для получения коодинат мыши на worldmap использует свою функцию `1001C060` вместо движковой `mouse_get_position_` в которой для получения корректнных x/y значений вычитается некое число из HRP.

_Нужно проверить правильность получения координат мыши из скрипта на глобальной карте._

**Просто вычитается положение окна интерфейса из текущих координат мыши.**

**Comment by NovaRain** [comment]
I guess that's for the terrain type display function?

**Comment by FakelsHub** [comment]
Yes.
Everything is fine, just subtracts the coordinates of the upper-left corner of the worldmap window interface from the x/y position of the mouse.
