### ISSUE TITLE
Операторы для беззнаковой проверки.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#31]
Попробовать добавить новый вид операторов для сравнения в компилятор.
`'<` `'>` `'>=` `'<=` 
`'` - символ указывающий что сравнение безнаковое.
И соответствующие функции к ним.

**Comment by burner1024** [comment]
Да вроде можно просто в ssl функции запилить и куда-нибудь в `lib.math.h` кинуть?

**Comment by FakelsHub** [comment]
Непонял какие функции в ssl пихнуть. Стандартные ssl операторы `>` `<` сравнивают с учетом знакового бита.

**Comment by burner1024** [comment]
Я имею ввиду наверное необязательно это на C++ писать, можно и SSL процедурами обойтись.

Да и на самом деле не знаю, пригодится ли. Для game_time все сравнения переделывать все равно накладно, а лимит только в 2 раза поднимается, потом время застывает и скрипты все равно корежит.

**Comment by NovaRain** [comment]
Maybe it's possible to script a procedure using bit operation to do the unsigned comparison? Something like (from [the post](https://stackoverflow.com/a/10097167)):
```
procedure comp(variable a, variable b) begin
   variable diff := a bwxor b;
   if (diff == 0) then begin
      display_msg("A is equal to B.");
      return;
   end

   diff := diff bwor (diff / 2);     // >> 1
   diff := diff bwor (diff / 4);     // >> 2
   diff := diff bwor (diff / 16);    // >> 4
   diff := diff bwor (diff / 256);   // >> 8
   diff := diff bwor (diff / 65536); // >> 16

   diff := diff bwand (bwnot(diff / 2) bwor 0x80000000);
   diff := diff bwand ((a bwxor 0x80000000) bwand (b bwxor 0x7FFFFFFF));

   if not(not(diff)) then display_msg("A is greater than B.");
   else display_msg("A is less than B.");
   // still doesn't work with negative values (> 0x7FFFFFFF)
end
```

EDIT:
My attempt on bit-shifting procedures:
```
procedure bwlsh(variable val, variable bits) begin
   return val * (2 ^ bits);
end

procedure bwrsh(variable val, variable bits) begin
   if (bits > 0) then begin
      if (val != -1) then begin
         val := (val / 2) bwand 0x7FFFFFFF;
      end else begin
         val := val - 0x80000000;
      end
      val := val / (2 ^ (bits - 1));
   end
   return val;
end
```
EDIT 2:
Hmm, this seems working:
```
procedure uint_comp(variable a, variable b) begin
   variable diff := a bwxor b;
   if (diff == 0) then begin
      display_msg("A is equal to B.");
      return;
   end

   diff := diff bwor bwrsh(diff, 1);
   diff := diff bwor bwrsh(diff, 2);
   diff := diff bwor bwrsh(diff, 4);
   diff := diff bwor bwrsh(diff, 8);
   diff := diff bwor bwrsh(diff, 16);

   diff := diff bwxor bwrsh(diff, 1);
   if (a bwand diff) then display_msg("A is greater than B.");
   else display_msg("A is less than B.");
end

call uint_comp(550, 128); // greater
call uint_comp(-2147483647, 100); // greater
call uint_comp(-1, -2147483647); // greater
```
So we can change uint_comp() to return 1 for greater, 0 for equal, and -1 for less.

**Comment by burner1024** [comment]
> Maybe it's possible to script a procedure using bit operation to do the unsigned comparison? 

Yes, that's what I'm saying. The feature doesn't seem so hot as to add it to the core.

**Comment by FakelsHub** [comment]
`bwrsh` - are not effective, too many unnecessary operations against a single div operation.

**Comment by FakelsHub** [comment]
Use macros:
```c++
#define above(a, b)        (unsigned_comp(a, b) > 0)
#define above_equal(a, b)  (unsigned_comp(a, b) >= 0)
#define below(a, b)        (unsigned_comp(a, b) < 0)
#define below_equal(a, b)  (unsigned_comp(a, b) <= 0)
```
```js
procedure unsigned_comp(variable a, variable b) begin
   variable result := a bwxor b;
   if (result == 0) then return result;

   result := result bwor (result / 2);     // >> 1
   result := result bwor (result / 4);     // >> 2
   result := result bwor (result / 16);    // >> 4
   result := result bwor (result / 256);   // >> 8
   result := result bwor (result / 65536); // >> 16

   return 1 if (a bwand (result bwxor (result / 2))) else -1;
end
```

**Comment by FakelsHub** [comment]
>  а лимит только в 2 раза поднимается, потом время застывает и скрипты все равно корежит.

почему застывает, там же опция есть отключения предела в 13 лет.
единственный косяк это скачек будет при сбросе счетчика.

**Comment by FakelsHub** [comment]
> Something like (from the post):

Looked at this post, you chose the ugliest not effective method))
this method is from the same post, and it seems to work too.
```js
procedure unsigned_comp(variable a, variable b) begin
   if ((a bwxor b) == 0) then return 0; // or a == b
   return 1 if ((b == 0) orElse (a / b)) else -1;
end
```

**Comment by NovaRain** [comment]
> Looked at this post, you chose the ugliest not effective method))

Yeah, the simpler seems working well. I was just trying to implement the one in the best answer.
A slightly uglier one in case someone still uses older compiler that doesn't recognize orElse:
```js
procedure unsigned_comp(variable a, variable b) begin
   if (a == b) then return 0;
   if (b == 0) then return 1;
   return 1 if (a / b) else -1;
end
```
If the macros and the procedure work, I suppose that should be enough? I think the unsigned comparison is only required in few specific cases, mostly `game_time` related.

**Comment by FakelsHub** [comment]
> A slightly uglier one in case someone still uses older compiler that doesn't recognize orElse

here need -s option.

**Comment by NovaRain** [comment]
> 
> 
> > A slightly uglier one in case someone still uses older compiler that doesn't recognize orElse
> 
> here need -s option.

I know. Just want to make one that can work  independent of the `-s` option (with `or`) or new short-circuit `orElse`.

**Comment by burner1024** [comment]
> почему застывает, там же опция есть отключения предела в 13 лет.
> единственный косяк это скачек будет при сбросе счетчика.

Ну да, game_time-то все равно сбросится назад, и скрипты на него полагающиеся пойдут вразнос. Чтобы реально улучшить ситуацию надо либо переходить на секунды вместо тиков, либо придумать какую-нибудь хитрость с game_time, чтобы укладывать его в 2 инта вместо одного.
А так, процедур и макросов более чем достаточно.

**Comment by FakelsHub** [comment]
64-бита нельзя сделать, секунды тоже, на этих тиках завязано все в игре.
Сделать можно отдельную функцию, как бы отсечь первые 8 бит (уменьшив точность) тем самым освободив место, чтобы получить псевдо 40 бит.
Правда кто будет заменять эти все функции на новую?))

**Comment by FakelsHub** [comment]
64-бита нельзя сделать, секунды тоже, на этих тиках завязано все в игре.
Сделать можно отдельную функцию, основанную на секундах.
Но кто будет заменять эти все функции на новую?)
Да и вообще это не особо то и нужно, это же не MMORPG играть так долго.

**Comment by burner1024** [comment]
> Да и вообще это не особо то и нужно, это же не MMORPG играть так долго.

Я согласен.

**Comment by FakelsHub** [comment]
Добавил макрос и процедуру в файл math.h
