### ISSUE TITLE
Применение параметров защиты от предмета брони к персонажу.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#37]
Изменить поведение применения параметров брони к персонажу, так чтобы броня установленная в слоте и ее параметры защиты не запекались в статистике персонажа, а каждый раз считывались непосредственно из прототипа предмета брони.
Это должно решить проблему несоответствия параметров при изменении параметров защиты брони при удалении(снятия) ее из слота во время игры.

**Comment by FakelsHub** [comment]
При реализации и применения данного метода потребуется дополнительная проверка на версию файла сохранения (в save.dat нужно добавить версию sfall), чтобы сохранить совместимость для старых сохранений для которых в данном случае должен работать ванильный метод.

**Comment by NovaRain** [comment]
You want to save the armor stats of each critter's worn armor in sfalldb.sav (or a new one?) and reset critter's armor stats (base/bonus) from its proto, then the armor data from .sav is only applied on the critter when the map loads?

**Comment by FakelsHub** [comment]
Do this as applied in other engines when the parameters of the armor are read not mediocre from its file and are summed up with the stats of the character,  and not baking armor defence stats into stats the character after the armor was put in slot.

With such a vanilla approach, it is fraught with bugs that we have previously fixed.

**Comment by NovaRain** [comment]
Seems to me you're going to rewrite many hacks/fixes to support summing up the armor stats on demand, so one can freely edit armor protos without worrying about equip/unequip armor would break party members' existing armor stats (mostly in bonus fields) in savegames.

**Comment by FakelsHub** [comment]
That's right, but I haven't looked at how many changes will be needed yet, it doesn't seem like a lot, just need to write one additional function in sfall.

**Comment by FakelsHub** [comment]
Кажется этот метод также имеет свои баги при получении и изменении статистики.
Example:
get: `total = critter_dmg_resist_laser + armour_dmg_stat_laser`
`total += 10` 
set: `critter_dmg_resist_laser = total`
again get: `total = critter_dmg_resist_laser + armour_dmg_stat_laser`
где `total` будет содержать уже неверное значение статистики.

Вариант будет правильным только с дополнительным вычитанием 
set: `critter_dmg_resist_laser = total - armour_dmg_stat_laser`

В общем это какая-то плохая идея. :) Но другого способа избавиться от бага движка не возможно.

**Comment by FakelsHub** [comment]
Так просто расчеты.
```
10 + 50 = 60
60 + 20% = 72 (12)
72 - 50 = 22
```

**Comment by NovaRain** [comment]
I don't quite follow you. Where is the calculation from?

**Comment by FakelsHub** [comment]
Алилуя. Родилась идея записывать значения одетой брони в отдельный блок и сохранять его.
Благо броня экипируется только для игрока и членов партии поэтому хранить данных для каждого криттера не потребуется.

_Aliluya. The idea was born to write the values of the dressed armor in a separate block and save it.
Fortunately, the armor is equipped only for the player and party members, so you do not need to store data for each critter._

**Comment by FakelsHub** [comment]
> 
> 
> I don't quite follow you. Where is the calculation from?

it's just a calculation taken from the pseudocode, modeled just as it was supposed to work.

**Comment by FakelsHub** [comment]
Отказ в реализации.
Причина малозначительный баг, который исправляется при правильном использовании функций скриптов, при модификации основного прототипа брони.
Исключение составляет сохраненная игра.
