### ISSUE TITLE
ID объектов и их указатели

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#4]
https://github.com/FakelsHub/sFall-Extended/blob/59b1b1b3ab1a86010f8d1a094eade0e52d7b443b/sfall/Modules/Skills.cpp#L234
Неправильная реализация, значения вектора должно быть очищено после выхода с карты. Потому как Id указатели криттеров не являются уникальными индификаторами.

**Comment by NovaRain** [comment]
Just curious, is there any practical example of the issue or something it could happen in theory?

**Comment by FakelsHub** [comment]
I don't know)
The script using set_critter_burst_disable is there > https://github.com/BGforgeNet/fo2tweaks

Добавил присвоение уникального идентификатора объектам,  с этим я думаю должно быть все в порядке. UID присваивается в диапазоне 0x10000000-7FFFFFFF.

Нужно будет добавить функцию для использования в скриптах, что бы была возможность присвоить объекту уникальный ID.

**Comment by NovaRain** [comment]
OK, guess I'll have to think a way to implement the fix for 3.8.

Could you take a look if I implemented it right for 3.8?
https://github.com/phobos2077/sfall/commit/2427634ee89314023d552ef7853cf1bf90272517

**Comment by FakelsHub** [comment]
Everything seems ok.

**Comment by FakelsHub** [comment]
Замечание.
Как выяснилось для предметов id не является перманентным значением, id меняется самой игрой когда предметы складываются в стопку  или вытаскиваются из стопки в инвентаре игрока.
https://github.com/FakelsHub/sFall-Extended/blob/42bf935a4633cee84ebd73c7bf478f7a9049b97b/sfall/Modules/Combat.cpp#L42

Необходимо сделать механизм сохранения уникального номера перед укладыванием в стопку, и востановление его после вытаскивания, для этого нужно найти неиспользуемое поле в параметрах объекта.

**Comment by FakelsHub** [comment]
У игрока ID всегда равен 18000 (устанавливается при инициализации игры)

**Comment by NovaRain** [comment]
Just curious, what kind of ID? Is there any way to check in game?

**Comment by FakelsHub** [comment]
>Is there any way to check in game?

get_object_data(obj, 0)

**Comment by NovaRain** [comment]
Oh, I just checked other NPC's UID. For example Vic's UID is 18062 in my old saves when I load the game, but because I have a global script keep running to disallow party members using burst attacks, now his UID will be changed to 268435457 shortly and saved in new saves.

т.е 268435457 = 0x10000001

**Comment by FakelsHub** [comment]
Можно использовать уникальные ID номера для решения проблемы использования наркотиков на  NPC, чтобы эффекты нераспосстранялись на других криттеров с одинаковым Pid.
Дополнительно нужно будет реализовать функционал  в модуле Drugs где будет храниться информация о примененных наркотиках Npc, так же эту информацию необходимо будет сохранять при сохранении игры, чтобы очередь отката эффектов корректно применялась, (сейчас очередь эффектов при загрузки сохраненной игры не работает для NPC.
При сохранении очереди эффектов используется ID объекта, и при загрузке сохраненной игры происходит поиск объекта с этим id. Но id  может быть найден от другого объекта, т.к. маппер2 имеет ошибку и  ID присваивается не правильно, т.е. на одной карта могут быть объекты с одинаковым ID.
Поэтому нужна система с уникальными ID.

**Comment by FakelsHub** [comment]
Необходимо проверить каким образом устанавливается ID для напарников, почему он всегда выше чем у игрока.
У партийцев ID устанавливается так: 18000 + номер его прототипа.

**Comment by FakelsHub** [comment]
Вроде как вся проблема с ID была уже решена.
