### ISSUE TITLE
Проблема с CombatControl

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#41]
[Описание](https://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-154#post-4387865):
> Я нашел ошибку в том, как функция CombatControl= потребляет окно перка.
> У меня есть запас на это. Я хочу поставить свой перк 6-го уровня на 9-й уровень в FO: et tu, чтобы я мог выбрать лучшие критические характеристики и бонусную скорострельность, так как оба навыка присутствуют на LVL 9, а на lvl 6 нет ничего важного. Я использую CombatControl=2. когда я активирую бой и пропускаю повороты моей партии NPC до конца боя, а затем открываю лист персонажей игрока, и окно boom banked perk исчезает. Я могу обойти это, так как я мог бы использовать RapidPerks Ниррана, чтобы получить перк "здесь и сейчас", чтобы дать мне больше окон перка, когда я достигну уровня 9, но это было бы скорее мошенничеством, кроме того, те, кто играет законно, были бы шокированы тем, что внезапно они теряют перк. @NovaRain это была ошибка в обычном sfall не так давно (хотя я не помню, была ли она исправлена) , я специально помню, что раньше писал о той же проблеме.
> 
> Я прилагаю сохраненную игру lvl 6 с banked perk window от Fallout et tu, сыгранную с sfall eXtended v4.2.6. (SAVE02)
> 
> РЕДАКТИРОВАТЬ:
> Нашел еще один баг-так называемый печально известный внезапный конец боя в разгар боя.
> 
> Проще говоря условия для того чтобы это произошло таковы:
> 1.CombatControl= включен
> 2.партия npc в настоящее время контролируется в боевом режиме
> 3.курсор наведения наведен на персонажа игрока (обитателя хранилища) при управлении партийным NPC в боевом режиме.
> 
> если вышеуказанные условия соблюдены, то боевой режим удивительным образом заканчивается, несмотря на то, что все еще враждебные твари присутствуют и даже атакуют. получил (SAVE03) просто перед боем с Гизмо в Фо et ту и sfall продлен. это легко проверить там ( после окончания боя вы телепортируетесь обратно к воротам джанктауна, как обычно, несмотря на то, что Гизмо и его охранник все еще живы). ( этот баг идет навстречу любому бою, а не только Гизмо ( это может быть простое нажатие кнопки "а" и Пробел + наведение курсора на обитателя хранилища, когда у него есть кто-то в партии).

**Comment by NovaRain** [comment]
So the first bug is losing saved perk point (open char screen can choose multiple perks) after switching control?
I don't have Et Tu installed so I test in RP to try to reproduce it:
1. set CombatControl=2, and use a global script with `set_perk_freq(1);` (for quicker test).
2. load a save and gain 3 levels by using a script give me lots of XP. Now I have 3 unused perks: when I open the char screen I can choose perks 3 times.
3. start the combat, skip turns through all party members, and the combat ends itself.
4. open the char screen but can still choose 3 perks.

Not sure about the second one, I tried it in RP with phobos build but seemed not able to reproduce:
1. set CombatControl=2.
2. load a save in the Den (with Vic and Sulik in my party)
3. start the combat and shoot a junkie, and end my turn.
4. control switched to Vic. I hover the aiming cursor to the player and nothing happens (can aim/attack the player normally).
5. load another save and try the combat in random encounter. Still the same.

**Comment by FakelsHub** [comment]
I haven't checked anything yet. I don't even know what kind of mistake he means.

**Comment by FakelsHub** [comment]
1. set CombatControl=2, and use a global script with `set_perk_freq(1);` (for quicker test).
     2. load a save and gain 3 levels by using a script give me lots of XP. Now I have 3 unused perks: when I open the char screen I can choose perks 3 times.
     3. start the combat, skip turns through all party members, and the combat ends itself.
     4. open the char screen but can still choose 3 perks.

I don't have any bug with this. my action
1. load save (any with party members)
2. can choose perks.
3. start the combat.
2. enter the char screen.
4. skip all the party members, the combat ends.
5. enter the char screen, can choose perks.
-----------------
1. load save (any with party members)
2. can choose perks.
3. start the combat.
4. skip all the party members, the combat ends.
5. enter the char screen, can choose perks.

???

**Comment by gustarballs1983** [comment]
Ok Nova and Mr.Stalin..
So. Mr.Stalin wanted me to drop a line on this bug i posted on NMA where player looses a perk window after combat turn with ControlCombat=2

well I narrowed it down a bit although I'm not sure anymore if it's an sfall issue.... tested this in multiple fallout 2 engine games 2, Resurrection,Nevada, and ET TU. so far this problem only happend to me in ET TU. i have no idea why, but other games on the same engine are not affected. Hard to say what's causing this. as for the setup I'm using both the .SVN  version and 1.2 standalone (with the exception that standalone 1.2 version has Sfall switched to extended for the UsePartySkills=1 option).
If You want to know more You need to say what exactly I'm sepose to describe.

**Comment by FakelsHub** [comment]
Send your ddraw.ini with which you have this problem in ET TU. Because I have no problems with your saves there.
you can even send a folder with used mods, maybe some mod is to blame.

Record a video of how it all happens, especially it is important for "end the combat when the cursor is on the player" - this is something incredible.

**Comment by gustarballs1983** [comment]
script mods I use although it happended without them as well.
[scripts.zip](https://github.com/FakelsHub/sFall-Extended/files/5029940/scripts.zip)
mods '.inis' f2res.ini and ddraw.ini
[Fallout1in2.zip](https://github.com/FakelsHub/sFall-Extended/files/5029951/Fallout1in2.zip)
 this is all from .SVN .

as for a video i'll have to make it first. I'll upload it later.

EDIT: 
ok where do I upload the video? .mkv is not supported as this forum extension....

the video is choppy and laggy as hell, bad quality too... my old potato almost turned into french fries when making it.

EDIT#2:
Ok I've pinned down the bug with 'end combat when looking at dude in npc's turn' . It's not sfall bug. this happens only if Et Tu's cheat debug menu is enabled in Lexx-made  .ini . This menu, when using 'binoculars' on the player, pops up a dialog menu, which has cheat/debug options. however when in combat and ControlCombat= is used to controll another critter when hovering over targeting cursor ends combat (but only if the debug menu =1 in the .ini) So no it's not an Sfall issue, but rather Lexx's debug script is causing this.

As for the bug of vanishing perk windows, when trying to record the video it became non-consistent, it actually took several tries to reproduce this bug. I'm not sure anymore about the conditions to cause this, perhaps some game lag causing perk window function not to be restored properly in time, and if not returned in time it simply vanishes? Beats me.. however while recording the video the perk window lagging to pop up is pretty much consistent.

EDIT#3:
@FakelsHub 
@NovaRain
mentioning just in case I'm getting unnoticed :p

**Comment by FakelsHub** [comment]
Perk loss bug in the script GL_Perk_Per.int

> this happens only if Et Tu's cheat debug menu is enabled in Lexx-made .ini . 

What is the debugging script where can I see it?

**Comment by Lexx2k** [comment]
That makes no sense. The cheat menu is just regular dialog procedures.
[cheats.h](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/headers/cheats.h) is included in [obj_dude.ssl](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/MAIN/OBJ_DUDE.ssl).

PS: Don't mind the horrible code in cheats.h ... it's an old Fixt script.

/Edit: Ok, I didn't read that you mean using the menu while in combat... well... don't do that. It was never working correctly ...

**Comment by FakelsHub** [comment]
I just wanted to see what leads to this behavior in combat.
`terminate_combat;` :1st_place_medal: :+1:

**Comment by gustarballs1983** [comment]
@Lexx2k 
well yeah but it's not about using the cheat menu but rather how it activates.
You see it activates on binoculars and fallout option 'combat looks' enables binocular function on targetting cursor.
and when controlling npc critter with ControlCombat=, and simply hovering over targetting cursor on dude, combat mode shuts down. the the debug script *could* be told not to initiate during combat mode.

@FakelsHub 
Please ask lexx for the script I have no idea which one it is. but i'm telling you it's got to do something with launching the debug dialog menu during combat. instead of launching the dialog menu it shuts combat. should be if_combat_not_initiated_then_launch_script. (r something like that [I'm not a programer so it's just a wild guess] otherwise we get this bug...

**Comment by Lexx2k** [comment]
Well, could have said that much earlier. :>
I never use this function, and I never control party members, and as the script was made by Fixt and is horrible, I didn't even look at it after moving it out of obj_dude.

**Comment by FakelsHub** [comment]
> You see it activates on binoculars and fallout option 'combat looks' enables binocular function on targetting cursor.

You have the "see in combat" option enabled, so this behavior is when you hover the cursor.

**Comment by gustarballs1983** [comment]
exactly.

**Comment by gustarballs1983** [comment]
which is why the script *could* be set to not launch when combat mode is active.

else we get combat termination as dialogues can't run in combat...

Although the strange thing is the debug menu does not pop up then only shuts down combat.

**Comment by Lexx2k** [comment]
> Although the strange thing is the debug menu does not pop up then only shuts down combat.

Because it's buggy... it never worked correctly and I never investigated or used it.
https://github.com/rotators/Fo1in2/commit/2d3d69aabf89bbd6628196fc9273e7a18ad2362f

**Comment by gustarballs1983** [comment]
that explains it right :p

So are You still pursuing the lost perk window or was this explained as well?

I'm going to check the game without GL_Perk_per.int although it's pretty clear it's *not* an sfall issue so I assume we can all moove on.

**Comment by Lexx2k** [comment]
I have no idea what gl_perk_per is. Guess whoever made that script should look into it.

**Comment by FakelsHub** [comment]
> Although the strange thing is the debug menu does not pop up then only shuts down combat.

Because scripts work like this, they don't break the combat immediately at the point where the command is specified - it's just a request to end combat, which will be executed after the procedure ends.
