### ISSUE TITLE
Quests.txt

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#45]
```
# quests.txt
#
# format of each line is:
#
#   location, description, gvar_index, display_threshold, completed_threshold
#
# where:
#
#   location is the number of the message in map.msg describing the location
#
#   description is the number of the message in quest.msg with the quest description.
#
#   gvar_index is the GVAR_* number for the variable controlling the quest.
#
#   display_threshold is the minimum value that the gvar must be for this quest
#     to be displayed in the pipboy.
#
#   completed_threshold is the minimum value that the gvar must be for this quest
#     to be shown as completed in the pipboy.
```

- [ ]  Добавить параметр `failure_threshold` - для обозначения квеcта который может быть установлен как "проваленый", окрашивая его текст более темным цветом.

**Comment by FakelsHub** [comment]
Добавить дополнительный параметр в `Quests.txt` нельзя, так как нарушится совместимость.
Тогда нужна будет функция скрипта _или специальный `Quests.ini`_.
```
failure_threshold is the minimum value that the gvar must be for this quest to be shown as failure in the pipboy.
```

**Comment by NovaRain** [comment]
What's the need of marking quests "failed" distinctly? It just gets "finished" (crossed out) with a different outcome.

**Comment by FakelsHub** [comment]
A quest that cannot be completed/passed, in the course of game situations, for example, an NPC was killed, or any other conditions.

**Comment by NovaRain** [comment]
> 
> 
> A quest that cannot be completed/passed, in the course of game situations, for example, an NPC was killed, or any other conditions.

I mean from another point of view the quest is still "finished" (cannot be advanced further), just the player doesn't get the reward.
Also, in vanilla games there are cases that the "quest failed" value is smaller than "quest completed". Using a _threshold_ for quest failed would require rewriting scripts to reorder quest stage values, so the failed threshold is always greater than completed. Or not using threshold but a fixed value for displaying failed quests in the pipboy? i.e. the quest value must be 5 for marking as failed.

**Comment by FakelsHub** [comment]
> Or not using threshold but a fixed value for displaying failed quests in the pipboy? i.e. the quest value must be 5 for marking as failed.

Yes.
`>=1 displayed, >=4 completed, >=10 failed`

**Comment by FakelsHub** [comment]
> Using a threshold for quest failed would require rewriting scripts to reorder quest stage values, so the failed threshold is always greater than completed.

you don't need to rewrite anything if the parameter wasn't set.

**Comment by NovaRain** [comment]
> 
> 
> > Or not using threshold but a fixed value for displaying failed quests in the pipboy? i.e. the quest value must be 5 for marking as failed.
> 
> Yes.
> `>=1 displayed, >=4 completed, >=10 failed`
> 
> 
> > Using a threshold for quest failed would require rewriting scripts to reorder quest stage values, so the failed threshold is always greater than completed.
> 
> you don't need to rewrite anything if the parameter wasn't set.

OK. What if a quest is `>=1 displayed, >=3 completed` in quests.txt, while in the scirpt it's =4 failed and =7 completed?

**Comment by FakelsHub** [comment]
Well, the value must be greater than completed_threshold.

**Comment by NovaRain** [comment]
> 
> 
> Well, the value must be greater than completed_threshold.

Then it does require reordering quest stage values in scripts if one wants to implement it for existing mods or vanilla game, in case there are quests with failed stage value less than completed. If it can just check a fixed stage value rather than a value threshold, it would be more useful as a supplement to the quests.txt IMO.
