### ISSUE TITLE
Регионы в окне.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#46]
Исправить/изменить реализацию регионов при выходе из региона курсора мышки (mouse leave еvent). Не всегда срабатывает событие.

**Comment by NovaRain** [comment]
What do you mean by the mouse leave event? Leaving from where?

**Comment by FakelsHub** [comment]
> What do you mean by the mouse leave event?

`AddRegionProc({string reg_name}, {procedure enter}, {procedure leave}, {procedure press}, {procedure release});`

**Comment by NovaRain** [comment]
Oh, do you have a test script for those _region_ functions? I can't find usage examples of them.

**Comment by FakelsHub** [comment]
I tried to use this in the new inventory filter, but later deleted the code, because this event is buggy.
https://github.com/FakelsHub/InventoryFilter/blob/227a2cf9b7608c8cc7d53520644b3e1755b05fc6/gl_InvenFilter.ssl#L1422

**Comment by NovaRain** [comment]
Thanks. I try enabling the lines and see the black window when hovering the cursor on the weight text area of the loot target. What's the case when the event fails in your test?

**Comment by FakelsHub** [comment]
Actions.
1 create a window. 
2 create a region to fit the window. 
3 bind procedures to enter/leave events and see how the leave event is triggered.
Two test: (bug):
1 reduce the size of the region by 10 pixels.
2.check the event triggering

technically, the leave event is triggered only when the cursor moves to another window (not the one where the region was created).

**Comment by NovaRain** [comment]
Ah, OK. Can confirm the leave event not being triggered if the region boundary is the same as the script window.

**Comment by FakelsHub** [comment]
Test script:
```c++
CreateWin("test1", 300, 200, 100, 100);
SelectWin("test1");
FillWin(0, 0, 1.0);
ShowWin;

CreateWin("test", 300, 300, 100, 100);
SelectWin("test");
FillWin(1.0, 0, 0);
FillRect(0, 0, 50, 50, 0, 1.0, 0);
AddRegion "testreg" { 0,0, 50,0, 50,50, 0,50 };
AddRegionProc("testreg", enter, leave, 0, 0);
ShowWin;
```
```c++
procedure enter begin
   display_msg("enter");
end

procedure leave begin
   display_msg("leave");
end
```
