### ISSUE TITLE
Разобраться в проблеме цветов субтитров.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#54]
https://github.com/phobos2077/sfall/discussions/372

**Comment by egornovivan** [comment]
Может Windows aero шалит? В некоторых старых играх он ломает палитру/цвета. Вот пример шалящего aero, игровой текст в розовом цвете вместо белого
https://youtu.be/EMW56CF01qE
А вот так оно должно выглядеть без aero
https://youtu.be/U72LscoEN00

**Comment by egornovivan** [comment]
Во время подготовки скриншотов для экспериментов с FSR, я заметил что на win7 палитру пидорасит во всех режимах кроме dx9 и при этом aero был выключен. Подобного говна на win10 я не видел.

**Comment by FakelsHub** [comment]
Попому, что в w10 MS исправили свое пидоравство.
На w7 нужно отдельным патчем заплатку ставить.

**Comment by FakelsHub** [comment]
Тут проблема не в виндовс а в том что человек не может подобрать цвет для субтитров, двиг какимто страным образом выбирает цвет.

**Comment by FakelsHub** [comment]
цвета в палитре 
1 индекс должен быть черным 0,0.0
255 индекс должен быть белым.
все еще существует проблема смешивания цветов, возможно, сам алгоритм движка работает плохо или ему не хватает необходимых цветов в палитре.
Я подозреваю, что цвета должны быть расположены от темного (0-индекс) до светлого (255-индекс), тогда смешивание, вероятно, сработает.
Нужно сделать дополнительную утилиту для проверки данного предположения.
