### ISSUE TITLE
Бесшовное воспроизведение музыки

### ISSUE THREAD

**Issue by egornovivan** [FalloutTeamX/sfall-Extended#55]
Было бы неплохо сделать так, чтобы при переходе между локациями с одинаковой музыкой, не прерывался трек и не запускался по новой, тогда игра будет ощущаться бесшовной в пределах городов. В операции сравнения названий треков, нужно будет привести их к общему регистру(или сравнивать без учёта регистра), а то в maps.txt черти что творится в разных модах. Или сравнивать по какому нибудь "soundid", если такие используются для музыки

**Comment by FakelsHub** [comment]
Смотрел, вроде можно сделать без особой попа-боль.

**Comment by egornovivan** [comment]
Подобную фичу видел в OpenXcom OXCE, она у них на загрузке сейвов работает

**Comment by FakelsHub** [comment]
Реализовал.

Требуется потом протестировать ситуацию:
Прыжок/переход в другой город с одинаковым именем трека, по задумке при переходе должен играть wind2, и трек карты должен начать воспроизводиться с начало.

Если есть такое сохранение буду рад его получить. А то не особо хочется симулировать данную ситуацию.

**Comment by egornovivan** [comment]
> по задумке при переходе должен играть wind2, и трек карты должен начать воспроизводиться с начало.

По поводу тестирования, думаю Кламат и квест Дантонов/Тора полностью покрывает все возможные варианты переходов с одинаковыми треками. В Арройо тоже не простые переходы с разными треками. В Дыре квест Лары телепортирует к церкви, в Модоке квест Гришэма телепортирует на спасение Браминов.

Сейвов для теста увы нету, да и сам я без своего компьютера до конца лета. Кстати, давно уже пора сделать скрипт который с интервалом в 5 секунд телепортирует Избранного на локации и на разные входы по отсортированному списку, а потом все это дело запустить в доккерах для поиска крашей и просадок fps

**Comment by FakelsHub** [comment]
Нужна телепортация из городa в другой город а не на пасдбища к браминам)

**Comment by egornovivan** [comment]
> из городa в другой

Эм. Ниодного такого квеста незнаю. Чем квест Лары негодится? Телепортация происходит в другую часть города, переход между этими частями прерывает трек и запускает по новой. Ситуация с телепортом из одного города в другой практически не встречается, а чтоб ещё и треки в этих городах были одинаковые, ну это совсем нереально. Может в каких-то глобальных модах и встречается, но я не припомню. Телепорт в другой "город" помню только в квесте с налетчиками на Город Убежища, но там музыка разная.

**Comment by egornovivan** [comment]
Вот два сейва из FE 3.8.1 Марипоза и АЗОС у обоих 07desert, если фичу реализовал на сейвлоаде, то сгодится для тестов
[savegame.zip](https://github.com/FakelsHub/sFall-Extended/files/6920110/savegame.zip)

**Comment by FakelsHub** [comment]
Спасибо. За подсказку.

**Comment by egornovivan** [comment]
Тут можешь сейв взять для RPUv21
`https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/111#issuecomment-892715724`

**Comment by FakelsHub** [comment]
Да уже не надо. Я сам скриптово прыгал, ибо нет таких переходов в игре.
