### ISSUE TITLE
Нужна заглушка для потерянной графики

### ISSUE THREAD

**Issue by egornovivan** [FalloutTeamX/sfall-Extended#56]
https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/106
Нужно что-то яркое и заметное, в фонлайне для таких целей использовали анимацию горящего человека

**Comment by egornovivan** [comment]
Оказывается не всё так просто, турели и растения пытаются ходить и этим засирают логи отсутствующими анимациями. В ветке оригинального sfall хотят вместо заглушки включить уведомление в игровом окне сообщений, но для этого требуется исправить ИИ растений и турелей или сделать список исключений для этих уведомлений.

**Comment by FakelsHub** [comment]
Ненужна никакая заглушка :)

**Comment by egornovivan** [comment]
> Ненужна никакая заглушка :)

Ну а как быть то? Нужно как-то уведомлять о том что нехватает frm

**Comment by FakelsHub** [comment]
Да ни как. 
Это и так уведомляется в логе при включенной отладке.

> Оказывается не всё так просто, турели и растения

Там много где не хватает анимаций. И не только в F2.

**Comment by egornovivan** [comment]
Ну ладно, будем через логи выискивать.
