### ISSUE TITLE
Исправления и дополнения.

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#58]
- [x] 1. **Добавить новый конфигурационный файл "Unarmed.ini":**
    * возможность изменять параметры встроенных unarmed атак
    * атаки рукой: ATKTYPE_PUNCH, ATKTYPE_STRONGPUNCH, ATKTYPE_HAMMERPUNCH, ATKTYPE_JAB, ATKTYPE_HAYMAKER, ATKTYPE_PALMSTRIKE, ATKTYPE_PIERCINGSTRIKE
    * атаки ногой: ATKTYPE_KICK, ATKTYPE_STRONGKICK, ATKTYPE_SNAPKICK, ATKTYPE_HIPKICK, ATKTYPE_POWERKICK, ATKTYPE_HOOKKICK, ATKTYPE_PIERCINGKICK
    * изменяемые параметры:
        * Req_Level - требование: уровень игрока [1..99]
        * Req_ST - требование: сила [1..99]
        * Req_AG - требование: ловкость [1..99]
        * Req_Unarmed - требование: навык ближнего боя [0..300]
        * AP - затраты Action Points на атаку
        * Dmg_Min - минимальный урон
        * Dmg_Max - максимальный урон / Bonus_Dmg - бонусный урон
        * Penetrate - наличие у атаки оружейного перка "Weapon: Penetrate" (DT/5)
        * Crit+ - дополнительный шанс критического урона
        * Slot - Main/Secondary (например, сейчас HAYMAKER - main, PIERCINGSTRIKE - second)

- [x] 2. **Исправить в инвентаре отображение урона встроенных атак ближнего боя для активного слота оружия:**
    * сейчас отображаемый урон не учитывает Dmg_Min и Dmg_Max встроенных unarmed атак (или всегда берёт значения ATKTYPE_PUNCH):
        * отображаемый урон = (1; 2 + bonus_melee_dmg)
        * реальный урон = (Dmg_Min; Dmg_Max + bonus_melee_dmg)
    * пример:
        * Haymaker (dmg 8-9), STR 10 (dmg +5), Heavy Handed (dmg +4), 3x Bonus HTH Damage (dmg +6)
        * отображаемый урон = 1-12 (7-12 при BonusHtHDamageFix=0)
        * реальный урон = 8-24 (14-24 при BonusHtHDamageFix=1)
- [ ]  3. **Исправить поведение переменной "ddraw.ini|Misc|BonusHtHDamageFix=1", которая влияет на минимальный урон unarmed/melee атак:**
    * было: добавляет урон только от перка bonus_hth_dmg, но урон от силы и трейта heavy_handed не добавляет
    * стало: добавляет урон от силы, трейта heavy_handed и перка bonus_hth_dmg (то есть весь bonus_melee_dmg)
**Отказ: Противоречит описанию.**

---
http://www.nuclear-city.com/index.php/topic/869-sfall-модернизация-игрового-движка-fallout-2/?p=90769

**Comment by NovaRain** [comment]
BonusHtHDamageFix was only for the Bonus HTH Damage perk itself, treating it like Bonus Ranged Damage that adds 2 points to raw damage instead of only affecting the maximum damage, because its description in-game implies it should work in the same way as Bonus Ranged Damage.
Seems to me you are planning to change all melee damage bonus (or the "Melee Damage" value displayed on the char screen) to add to both the minimum and maximum damage?

In Fallout 2 manual, it says:

> Melee Damage - This is the amount of damage added to the **upper end** of hand-to-hand and melee attacks. It is possible to have a Melee Damage of 5 and still do only one point of damage when you attack, based on armor and the fact that **this stat adds to the maximum amount of random damage done, not the minimum**.

**Comment by FakelsHub** [comment]
Готово.
