### ISSUE TITLE
Hook RemoveObj

### ISSUE THREAD

**Issue by FakelsHub** [FalloutTeamX/sfall-Extended#6]
Необходимо добавить дополнительный аргумент со значением указывающий в какой объект будет перемещен предмет.

**Comment by NovaRain** [comment]
Isn't arg2 of HOOK_REMOVEINVENOBJ the object being removed?

**Comment by FakelsHub** [comment]
critter arg1 - the critter the object is being removed from (source)
item    arg2 - the item that is being removed
int     arg3 - a flag, or possibly the number of items to remove
int     arg4 - The reason the object is being removed. (Flag)

Need add arg5 - items moved to critter/object (source >> destination)

**Comment by FakelsHub** [comment]
Done.
